### ISSUE TITLE
Body only provide json, not support other Content-type

### ISSUE THREAD

**Issue by mrapry** [Bhinneka/gubrak#15]
**Current Version**
In the current version, we can set the body with json format. like that 
`{
    "url": "http://example.com",
    "headers": {
        "Authorization": "Basic exnfekeoeoeojsjalaljahhd",
        "Content-Type": "application/json",
        "Accept": "application/json"
    },
	"payload": {
		"from": "Bob",
		"content": {
			"header": "This is Message 3",
			"body": "Hello There"
		}
	}
}`

It is better for the next version, the body data is also added with Content-type like form-data, x-www-from-urlencoded. Thanks

**Comment by wuriyanto48** [comment]
solve,
please upgrade your gubrak @mrapry ..

**Comment by mrapry** [comment]
Thanks
