### ISSUE TITLE
panic: send on closed channel when one or more http: request timeout

### ISSUE THREAD

**Issue by wuriyanto48** [Bhinneka/gubrak#8]
`panic: send on closed channel

goroutine 160 [running]:
github.com/Bhinneka/gubrak.Scan.func1(0xc0000b4030, 0xc0000a6424, 0x3, 0x7ffeefbff964, 0x10, 0xc0000a0e10, 0xc0000b62a0, 0xc000122d20)
	/Users/wurianto/Documents/go-work/src/github.com/Bhinneka/gubrak/worker.go:30 +0xd6
created by github.com/Bhinneka/gubrak.Scan
	/Users/wurianto/Documents/go-work/src/github.com/Bhinneka/gubrak/worker.go:28 +0xa3
panic: send on closed channel`

**Comment by wuriyanto48** [comment]
@bxcodec , does this **panic** happened to you? 😄

**Comment by bxcodec** [comment]
Maybe, removing the close channel will fix this
